Repository kubernetes-sigs/cloud-provider-equinix-metal, pull requests merged in 2023-10, with the labels that each got.

#463 refactor: cleanup of cpem
  deploy/template/deployment.yaml
  go.mod
  go.sum
  main.go
Labels: size/L, cncf-cla: yes, approved

#471 feat: add beta SDK for Equinix Metal Load Balancer service
  internal/lbaas/v1/.gitignore
  internal/lbaas/v1/.openapi-generator-ignore
  internal/lbaas/v1/.openapi-generator/FILES
  internal/lbaas/v1/.openapi-generator/VERSION
  internal/lbaas/v1/api_load_balancers.go
  internal/lbaas/v1/api_origins.go
  internal/lbaas/v1/api_pools.go
  internal/lbaas/v1/api_ports.go
  internal/lbaas/v1/api_projects.go
  internal/lbaas/v1/client.go
  internal/lbaas/v1/configuration.go
  internal/lbaas/v1/model_load_balancer.go
  internal/lbaas/v1/model_load_balancer_collection.go
  internal/lbaas/v1/model_load_balancer_create.go
  internal/lbaas/v1/model_load_balancer_location.go
  internal/lbaas/v1/model_load_balancer_pool.go
  internal/lbaas/v1/model_load_balancer_pool_collection.go
  internal/lbaas/v1/model_load_balancer_pool_create.go
  internal/lbaas/v1/model_load_balancer_pool_create_protocol.go
  internal/lbaas/v1/model_load_balancer_pool_origin.go
  internal/lbaas/v1/model_load_balancer_pool_origin_collection.go
  internal/lbaas/v1/model_load_balancer_pool_origin_create.go
  internal/lbaas/v1/model_load_balancer_pool_origin_port_number.go
  internal/lbaas/v1/model_load_balancer_pool_origin_update.go
  internal/lbaas/v1/model_load_balancer_pool_protocol.go
  internal/lbaas/v1/model_load_balancer_pool_short.go
  internal/lbaas/v1/model_load_balancer_pool_update.go
  internal/lbaas/v1/model_load_balancer_port.go
  internal/lbaas/v1/model_load_balancer_port_collection.go
  internal/lbaas/v1/model_load_balancer_port_create.go
  internal/lbaas/v1/model_load_balancer_port_update.go
  internal/lbaas/v1/model_load_balancer_short.go
  internal/lbaas/v1/model_load_balancer_update.go
  internal/lbaas/v1/model_provider.go
  internal/lbaas/v1/model_resource_created_response.go
  internal/lbaas/v1/response.go
  internal/lbaas/v1/utils.go
Labels: cncf-cla: yes, size/XXL

#470 feat: add support for Equinix Metal Load Balancer
  .gitignore
  Dockerfile
  README.md
  dev/Tiltfile
  dev/cloud-sa.json
  dev/web-updated.yaml
  dev/web-updated2.yaml
  dev/web.yaml
  dev/words.sql
  dev/wordsmith-ingress.yaml
  go.mod
  go.sum
  metal/cloud.go
  metal/config.go
  metal/controlplane_load_balancer_manager.go
  metal/loadbalancers.go
  metal/loadbalancers/emlb/emlb.go
  metal/loadbalancers/emlb/infrastructure/manager.go
  metal/loadbalancers/emlb/infrastructure/token_exchanger.go
  metal/loadbalancers/empty/empty.go
  metal/loadbalancers/interface.go
  metal/loadbalancers/kubevip/kubevip.go
  metal/loadbalancers/metallb/metallb.go
Labels: cncf-cla: yes, size/XXL

#474 fix: return a valid LoadBalancerStatus for BGP-based load balancers
  metal/loadbalancers.go
Labels: size/XS, cncf-cla: yes, approved, lgtm

#475 fix: use the correct external port for control plane LBs
  metal/controlplane_load_balancer_manager.go
Labels: size/S, cncf-cla: yes, approved, lgtm
